### ISSUE TITLE
video freezes after some frames in video_loop mode

### ISSUE THREAD

**Issue by yuyou** [ricohapi/libuvc-theta-sample#2]
Hi

The sample works nicely in the gst_view mode. But the player side (gstreamer) freezes after few frames when running in the loopback mode with v4l2loopback installed.

The code uses the same Gstreamer pipeline so I dont know why it freezes.

OS: Ubuntu 18.04
GStreamer: 1.16.2 

The v4l2 loopback works fine when testing a fake sender  like:
`gst-launch-1.0 videotestsrc is-live=true pattern=ball ! v4l2sink device=/dev/video0 sync=false`

The player script:
`gst-launch-1.0 v4l2src device=/dev/video0 ! autovideosink sync=false`

**Comment by yuyou** [comment]
I found the fix.

Add qos=false makes it work. I tested it on Ubuntu 18/20 on laptop/desktops.

`device=/dev/video0 qos=false sync=false`

https://github.com/ricohapi/libuvc-theta-sample/blob/f8c3caa32bf996b29c741827bd552be605e3e2e2/gst/gst_viewer.c#L190

**Comment by codetricity** [comment]
I think this issue can be closed as I haven't heard of any problems after implementing the fix suggested by YuYou.  Also, hardware acceleration does need to be enabled to get good latency and people should check using nvidia-smi or equivalent on x86 laptop/desktops.

**Comment by nonlinear1** [comment]
@yuyou I have installed libuvc-theta and libuvc-theta-sample. But when I run  ./gst_viewer of the libuvc-theta-sample, I received the error: 
start, hit any key to stop
Error: Internal data stream error.
stop
 and I test the libuvc-theta with running example. It give me the following message:
UVC initialized
Device found
Device opened
DEVICE CONFIGURATION (05ca:2712/01104169) ---
Status: idle
VideoControl:
	bcdUVC: 0x0150
VideoStreaming(1):
	bEndpointAddress: 132
	Formats:
	Unknown(1)
		  bits per pixel: 0
		  GUID: 4832363400001000800000aa00389b71 (H264)
		  default frame: 1
		  aspect ratio: 1x1
		  interlace flags: 00
		  copy protect: 00
			FrameDescriptor(1)
			  capabilities: 25
			  size: 3840x1920
			  bit rate: 600000-240000000
			  max frame size: 0
			  default interval: 1/29
			  interval[0]: 1/29
			FrameDescriptor(2)
			  capabilities: 25
			  size: 1920x960
			  bit rate: 600000-20000000
			  max frame size: 0
			  default interval: 1/29
			  interval[0]: 1/29
END DEVICE CONFIGURATION

First format: (H264) 3840x1920 29fps
bmHint: 0000
bFormatIndex: 128
bFrameIndex: 0
dwFrameInterval: 0
wKeyFrameRate: 46591
wPFrameRate: 240
wCompQuality: 0
wCompWindowSize: 0
wDelay: 1
dwMaxVideoFrameSize: 0
dwMaxPayloadTransferSize: 2184745645
bInterfaceNumber: 245
get_mode: Invalid mode (-51)
Device closed
UVC exited

 So I think the uvc driver is good. Could you tell you how to solve this problem? Thank you very much!

**Comment by codetricity** [comment]
In the case of the OP, he fixed it with `qos=false` in the pipeline for gst_loopback that is sent to v4l2loopback.  

Please take the discussion to this thread:
https://community.theta360.guide/t/live-streaming-over-usb-on-ubuntu-and-linux-nvidia-jetson/4359?u=craig

On the forum, please provide this information:

1. are you using `gst_viewer` or `gst_loopback`?  Note that the closed thread in this issue is for loopback, not for `gst_viewer`.  If you don't know the difference, post to the forum and we can provide more explanation.
2.  print the output of `lsusb` including the line that shows the device ID as 05ca:2712 Ricoh Co., Lt for V or 2715 for Z1.

![device](https://community.theta360.guide/uploads/default/original/2X/1/1a15ab70e95b28f7d1e600c3c0fdfc0f94afdaff.png)

If the device ID is anything other than 2712 or 2715, the program will not run.

You can scan through the code and see that it's looking for the ID.

https://github.com/ricohapi/libuvc-theta-sample/blob/f8c3caa32bf996b29c741827bd552be605e3e2e2/gst/thetauvc.c#L104

**Comment by nonlinear1** [comment]
Thank you very much! I will try
